clear ALL;
clc;
netFolder = fullfile('C:\Users\IT\Desktop\paul\Gender1Classification');
matFileName = fullfile(netFolder, 'genderIDNet.mat');
load(matFileName,'genderIDNet','M','S');
makeAudio1()
[audioIn,Fs] = audioread('audio2.wav');
boundaries = detectSpeech(audioIn,Fs);
audioIn = audioIn(boundaries(1):boundaries(2));
extractor = audioFeatureExtractor( ...
    "SampleRate",Fs, ...
    "Window",hamming(round(0.03*Fs),"periodic"), ...
    "OverlapLength",round(0.02*Fs), ...
    ...
    "gtcc",true, ...
    "gtccDelta",true, ...
    "gtccDeltaDelta",true, ...
    ...
    "SpectralDescriptorInput","melSpectrum", ...
    "spectralCentroid",true, ...
    "spectralEntropy",true, ...
    "spectralFlux",true, ...
    "spectralSlope",true, ...
    ...
    "pitch",true, ...
    "harmonicRatio",true);
features = extract(extractor,audioIn);
features = (features.' - M)./S;
gender = classify(genderIDNet,features);
message = 'Your gender is: %s';
result = sprintf(message,gender)


